site_name: CSBEF
theme: 
    name: 'material'
    highlightjs: true
    language: "en"
nav:
    - Home: 'index.md'
    - Türkçe Dokümantasyon:
        - Nedir: 'TR/what-is-csbef.md'
        - Library:
            - Abstracts:
                - RepositoryBase: 'TR/library/Abstracts/RepositoryBase.md'
                - ServiceBase: 'TR/library/Abstracts/ServiceBase.md'
            - Concretes:
                - APIStartServiceCollection: "TR/library/Concretes/APIStartServiceCollection.md"
                - EventService: "TR/library/Concretes/EventService.md"